name: Build

on:  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:  
  build:    
    runs-on: windows-latest  

    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: msbuild.exe sdk-dotnet.sln /t:Restore /p:configuration="Release"
        
      - name: Build
        run: msbuild.exe sdk-dotnet.sln /t:Build /p:configuration="Release"
        
      - name: Create Nuget package
        run: msbuild.exe sdk-dotnet.sln /t:Pack /p:configuration="Release"        
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: DataMeshGroup.Fusion/bin/Release/*.nupkg
          
         
  publish:              
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: nugetpath
          
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3          
  
      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "nugetpath" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.PUBLISH_NUGET_SECRET }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }       
